dcrm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('Davy_The_Admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.urls import path, include
from . import views
from .view.dashboard import dashboard

urlpatterns = [
    path('', dashboard, name='home'),
    path('login/', views.login_page, name='login_page'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('user_manual/', views.user_manual_view, name='user_manual'),

    path('record/<int:pk>', views.customer_record, name='record'),
    # path('delete_record/<int:pk>', views.delete_record, name='delete_record'),
    # path('add_record/', views.add_record, name='add_record'),
    path('data_logs_devices/', views.data_logs_devices, name='data_logs_devices'),
    path('data_logs/<int:pk>', views.data_logs, name='data_logs'),


    path('devices/', views.devices, name='devices'),
    path('dashboard/', dashboard, name='dashboard'),

    path('add_device/', views.add_device, name='add_device'),
    path('update_device/<int:pk>', views.update_device, name='update_device'),
    path('delete_device/<int:pk>', views.delete_device, name='delete_device'),
    path('discover_ip', views.discover_ip, name='discover_ip'),

    path('addresses/', views.addresses, name='addresses'),
    path('register_addresses/<int:pk>', views.register_addresses, name='register_addresses'),
    path('delete_addresses/<int:pk>', views.delete_addresses, name='delete_addresses'),
    path('update_address/<int:pk>', views.update_address, name='update_address'),

    path('charts/', views.charts, name='charts'),

    path('reports/', views.reports, name='reports'),
    path('add_report/', views.add_report, name='add_report'),
    path('delete_report/<int:pk>', views.delete_report, name='delete_report'),
    path('update_report/<int:pk>', views.update_report, name='update_report'),
    path('send-report/<int:report_id>/', views.trigger_email_report, name='send_report'),
    path('download-report/<int:report_id>/', views.trigger_download_report, name='download_report'),

    path('alarms/', views.alarms, name='alarms'),
    path('pre_add_alarm/', views.pre_add_alarm, name='pre_add_alarm'),
    path('add_alarm/<int:pk>', views.add_alarm, name='add_alarm'),
    path('update_alarm/<int:pk>', views.update_alarm, name='update_alarm'),
    path('delete_alarm/<int:pk>', views.delete_alarm, name='delete_alarm'),
    path('reset_alarm/<int:pk>', views.reset_alarm, name='reset_alarm'),

    path('user_page/', views.user_page, name='user_page'),

    path('historical_data_logs/', views.historical_data_logs, name='historical_data_logs'),
    path('historical_data/<str:table_name>/', views.historical_data, name='historical_data'),
    path('historical-data/<str:table_name>/<int:device_id>/', views.historical_data_by_device_id, name='historical_data_by_device_id'),
    
    path('diagrams', views.diagrams, name='diagrams'),
    path('diagrams/<int:pk>', views.diagrams_device, name='diagrams_device'),
    path('diagrams_chart_data/<str:name>/', views.diagrams_chart_data, name='diagrams_chart_data'),
    path('diagrams_chart_graph/<str:name>/', views.diagrams_chart_graph, name='diagrams_chart_graph'),
    path('diagrams_chart_graph_2/<str:name>/', views.diagrams_chart_graph_2, name='diagrams_chart_graph_2'),
    path('device-tree/', views.device_tree_view, name='device_tree_view'),
    path('device_tree_view_element/<int:pk>', views.device_tree_view_element, name='device_tree_view_element'),
]

website/models.py
from django.db import models
from django.utils import timezone

class Record(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    Address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=20)

    def __str__(self):
        return (f'{self.first_name} {self.last_name}')
    

class Voltage(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    L1 = models.CharField(max_length=20)
    frequency = models.CharField(max_length=20)

    def __str__(self):
        return (f"{self.created_at} {self.L1}")
    
class Company(models.Model):
    company_name = models.CharField(max_length=50)
    company_discreption = models.CharField(max_length=100)
    num_devices = models.CharField(max_length=10)
    licence_type = models.CharField(max_length=50)

    def __str__(self):
        return (f"{self.company_name} {self.company_discreption}")
        


# class TriggredAlarms(models.Model)
    
class Device(models.Model):
    company_name = models.CharField(max_length=50)
    device_name = models.CharField(max_length=50)
    connection_type = models.CharField(max_length=30)
    port_conf = models.CharField(max_length=30)
    device_status = models.CharField(max_length=30)

    stop_bits = models.CharField(max_length=5)
    byte_size = models.CharField(max_length=5)
    parity = models.CharField(max_length=5)
    baud_rate = models.CharField(max_length=15)
    timeout = models.CharField(max_length=5)

    ip_address = models.CharField(max_length=50)
    signals = models.CharField(max_length=30)
    manufacturer = models.CharField(max_length=50)

    group = models.CharField(max_length=15)

    def __str__(self):
        return (f"{self.device_name}")


class Report(models.Model):
    # channel = models.ManyToManyField(Device)
    report_status = models.CharField(max_length=30)
    report_device = models.TextField()
    report_measure = models.TextField()
    # report_interval = models.CharField(max_length=30)
    report_interval_hours = models.CharField(max_length=30)
    report_interval_minutes = models.CharField(max_length=30)
    report_description = models.TextField()
    report_activation = models.CharField(max_length=30)
    report_emails = models.CharField(max_length=30)
    report_timezone = models.CharField(max_length=30)

    report_date_type = models.CharField(max_length=50)
    # report_date_from = models.DateField()
    # report_date_to = models.DateField()

class Alarm(models.Model):
    channel = models.ForeignKey(Device, on_delete=models.CASCADE)
    alarm_status = models.CharField(max_length=30)
    alarm_device = models.CharField(max_length=30)
    alarm_measure = models.CharField(max_length=50)
    alarm_description = models.TextField()
    alarm_min = models.CharField(max_length=30)
    alarm_max = models.CharField(max_length=30)
    alarm_activation = models.CharField(max_length=30)
    alarm_emails = models.CharField(max_length=50)
    alarm_trigger = models.CharField(max_length=50, default='No')
    alarm_triggered_at = models.CharField(max_length=50, default='')

class AlarmTrigger(models.Model):
    trigger_device = models.ForeignKey(Device, on_delete=models.CASCADE)
    trigger_alarm = models.ForeignKey(Alarm, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    trigger_name = models.CharField(max_length=30)
    trigger_data = models.CharField(max_length=30)

class Register(models.Model):
    channel = models.ForeignKey(Device, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    register_address = models.CharField(max_length=15)
    num_of_registers = models.CharField(max_length=15)
    dividing_parameter = models.IntegerField()
    polling_interval = models.CharField(max_length=50)
    parameter_name = models.CharField(max_length=50)
    
    def __str__(self):
        return (f"{self.name} {self.channel}")
    

class ModbusData(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    register = models.ForeignKey(Register, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    register_address = models.IntegerField()
    value = models.CharField(max_length=30)
    polling_interval = models.CharField(max_length=50)

class License(models.Model):
    encrypted_license_key = models.CharField(max_length=255, unique=True)
    max_devices = models.IntegerField(default=40)

    def __str__(self):
        return f"License - {self.encrypted_license_key}"


class MasterEmail(models.Model):
    email = models.TextField()


class Diagram_Charts(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    chart_1_title = models.CharField(max_length=50)

    chart_1_1 = models.CharField(max_length=50)
    chart_1_max = models.IntegerField(default= 1)
    chart_1_min = models.IntegerField(default= 1)
    chart_1_thresh_hold = models.IntegerField(default= 1)

    chart_1_2 = models.CharField(max_length=50)
    chart_1_3 = models.CharField(max_length=50)
    chart_1_4 = models.CharField(max_length=50)
    chart_1_5 = models.CharField(max_length=50)

    chart_2_title = models.CharField(max_length=50)
    chart_2_max = models.IntegerField(default= 1)
    chart_2_min = models.IntegerField(default= 1)
    chart_2_thresh_hold = models.IntegerField(default= 1)

    chart_2_1 = models.CharField(max_length=50)
    chart_2_2 = models.CharField(max_length=50)
    chart_2_3 = models.CharField(max_length=50)
    chart_2_4 = models.CharField(max_length=50)
    chart_2_5 = models.CharField(max_length=50)

    chart_3_title = models.CharField(max_length=50)
    chart_3_max = models.IntegerField(default= 1)
    chart_3_min = models.IntegerField( default= 1)
    chart_3_thresh_hold = models.IntegerField(default= 1)

    chart_3_1 = models.CharField(max_length=50)
    chart_3_2 = models.CharField(max_length=50)
    chart_3_3 = models.CharField(max_length=50)
    chart_3_4 = models.CharField(max_length=50)
    chart_3_5 =models.CharField(max_length=50)

    chart_4_title = models.CharField(max_length=50)
    chart_4_max = models.IntegerField(default = 1)
    chart_4_min = models.IntegerField(default= 1)
    chart_4_thresh_hold = models.IntegerField(default= 1)
    
    chart_4_1 = models.CharField(max_length=50)
    chart_4_2 = models.CharField(max_length=50)
    chart_4_3 = models.CharField(max_length=50)
    chart_4_4 = models.CharField(max_length=50)
    chart_4_5 = models.CharField(max_length=50)

    chart_5_title = models.CharField(max_length=50)
    chart_5_max = models.IntegerField(default = 1)
    chart_5_min = models.IntegerField(default= 1)
    chart_5_thresh_hold = models.IntegerField(default= 1)
    
    chart_5_1 = models.CharField(max_length=50)
    chart_5_2 = models.CharField(max_length=50)
    chart_5_3 = models.CharField(max_length=50)
    chart_5_4 = models.CharField(max_length=50)
    chart_5_5 =models.CharField(max_length=50)

    chart_6_title = models.CharField(max_length=50)
    chart_6_max = models.IntegerField(default = 1)
    chart_6_min = models.IntegerField(default= 1)
    chart_6_thresh_hold = models.IntegerField(default= 1)

    chart_6_1 = models.CharField(max_length=50)
    chart_6_2 = models.CharField(max_length=50)
    chart_6_3 = models.CharField(max_length=50)
    chart_6_4 = models.CharField(max_length=50)
    chart_6_5 = models.CharField(max_length=50)

    graph_1 = models.TextField()
    graph_2 = models.TextField()


class Electrical_Bill(models.Model):
    devices = models.TextField()
    measures = models.TextField()

website/templates/add_record.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 offset-md-3"></div>
<h1>add record</h1>
<br />

<form method="POST" action="{% url 'add_record' %}">
    {% csrf_token %}
    {{ form.as_p }}
    </br>
    <button type="submit" class="btn btn-primary">Add Record</button>
</form>

{% endblock %}

website/templates/add_report.html
{% extends 'base.html' %}
{% block content %}


<script>
    $('select').selectpicker();
  </script>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

{{ form.media }}


<div class="col-md-6 offset-md-3">
    <h1 style="text-align: center;">Add Report</h1>
    <br />

    <form method="POST" action="{% url 'add_report' %}" class="row g-4">
        {% csrf_token %}
        <div class="col-md-6"> Devices
            {{ form.report_device }}
        </div>
        <div class="col-md-6"> Measures
            {{ form.report_measure }}
        </div>
        <div class="col-md-12">
            Description
            {{ form.report_description }}
        </div>

        <div class="col-md-4">
            Report Day
            {{ form.report_activation }}
        </div>
        <div class="col-md-4">
            Hour
            {{ form.report_interval_hours }}
        </div>
        <div class="col-md-4">
            Minute
            {{ form.report_interval_minutes }}
        </div>

        <div class="col-md-6">
            Email
            {{ form.report_emails }}
        </div>
        <div class="col-md-6">
            TimeZone
            {{ form.report_timezone }}
        </div>
        <div class="col-md-6">
            Status
            {{ form.report_status }}
        </div>

        <div class="col-md-6">
            Date Type
            {{ form.report_date_type }}
        </div>


        <button type="submit" class="btn btn-primary">Create Report</button>
    </form>
</div>

<script>
    $(document).ready(function() {
        function updateMeasureOptions() {
            var selectedDevices = $('#id_report_device').val();
            var allMeasures = $('#id_report_measure option');
            console.log(selectedDevices)
            allMeasures.each(function() {
                var measure = $(this);
                measureDevices = measure.val()
                
                if (selectedDevices == null){
                    measure.hide();
                }
                else if (selectedDevices.some(device => measureDevices.includes(device))) {
                    measure.show();
                } else {
                    measure.hide();
                }
            });

            $('#id_report_measure').selectpicker('refresh');
        }

        $('#id_report_device').on('changed.bs.select', updateMeasureOptions);
        updateMeasureOptions(); // Initial call to set the correct state
    });
</script>

{% endblock %}

website/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome-free-6.5.2-web\css\all.min.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EnergyEye</title>
    <link rel="icon" href="{% static 'images/logo01_Icon.png' %}">
    <link href="{% static 'bootstrap-5.3.3-dist\css\bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'bootstrap-5.3.3-dist\js\bootstrap.min.js' %}"></script>

    <link rel="stylesheet" href="{% static 'CSS/base.css' %}">
</head>

<style type="text/css">
    .footer-images {
        margin: auto;
        display: block;
        position: absolute;
        bottom: 0;
    }

    .footer-images .copyright {
        text-align: center;
    }

    #sidebar {
        position: -webkit-sticky;
        position: sticky;
        width: 13vw;
    }

    #SideText {
        color: white;
        text-decoration: none;
        font-size: 1.00vw;
    }


    #base_drop_down {
        display: none;
        opacity: 0;
        transition: opacity 5s ease, transform 0.5s ease;
        transform: translateY(-1px);
    }

    .nav-item:hover #base_drop_down {
        display: block;
        opacity: 1;
        transform: translateY(1.2);
        
    }
    .nav-item {
        position: relative;
    }

</style>


<body onload="startTime()">
    <!-- <div class="container"> -->
    <!-- </br> -->
    <nav id="navbar_id" class="navbar navbar-expand-lg navbar-dark sticky-top" style="z-index: 5; background-color: #23272b; height: 10vh; position: fixed; width: 100%;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                <h2><b>EnergyEye</b></h2>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    {% if user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_page' %}">{{ user.username }} <span
                                class="icon is-small"><i class="fa-solid fa-user"></i></span></a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_manual' %}" target="_blank"> Manual <span
                                class="icon is-small"><i class="fa-solid fa-circle-info"></i></span></a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>


                    {% else %}
                    <!-- <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li> -->

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Login</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link btn btn-secondary dropdown-toggle" role="button" id="dropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="{% url 'alarms' %}">
                        <marquee behavior="scroll" direction="left" style="width: 7vw;">{{ alarms_string }}</marquee> {{num_triggred_alarms }} <span class="icon is-small"><i class="fa-solid fa-bell"></i></span>
                    </a>

                    <div class="dropdown-menu" id="base_drop_down" aria-labelledby="dropdownMenuLink">
                            {% for alarm in alarm_record_base %}
                                <a class="dropdown-item" href="{% url 'alarms' %}">{{ alarm.alarm_device }}</a>
                            {% endfor %}
                    </div>
                </li>


                {% endif %}
                <li class="nav-item">
                    <spam class="nav-link active" id="Date"></spam>
                </li>

            </ul>
        </div>
    </nav>

    <!-- Side Navbar Area -->
    {% if user.is_authenticated %}
    <div class="wrapper">
        <div class="columns">
            <aside class="column is-1 aside" id="sidebar" style="position: sticky; overflow-y: auto; top: 10vh;">
                <nav class="menu">
                    <ul style="padding-top: 1vh; padding-left: 1vw;">
                        <li style="line-height: 1px"><a id="SideText" href="{% url 'dashboard' %}"><span class="icon is-small"><i
                                        class="fa-solid fa-square-poll-horizontal"></i></span> &nbsp; Dashboard</a></li>
                        <br>
                        <li style="line-height: 1px"><a id="SideText" href="{% url 'devices' %}"><span class="icon is-small"><i
                                        class="fa fa-desktop"></i></span> &nbsp; Devices</a></li>
                        <br>
                        <li style="line-height: 1px"><a id="SideText" href="{% url 'addresses' %}"><span class="icon is-small"><i
                                        class="fa-solid fa-terminal"></i></span>
                                &nbsp; Register Addresses</a></li>
                        <br>
                        <li style="line-height: 1px"><a id="SideText" href="{% url 'data_logs_devices' %}"><span class="icon is-small"><i
                                        class="fa fa-table"></i></span>
                                &nbsp; Data logs</a></li>
                        <br>

                        <!-- <li><a id="SideText" href="{% url 'charts' %}"><span class="icon is-small"><i
                                        class="fa-solid fa-chart-line"></i></span> &nbsp; Charts</a></li> -->
                        <!-- <br> -->
                        <li style="line-height: 1px"><a id="SideText" href="{% url 'alarms' %}"><span class="icon is-small"><i
                                        class="fa-solid fa-triangle-exclamation"></i></span> &nbsp; Alarms</a></li>
                        <br>
                        <li style="line-height: 1px"><a id="SideText" href="{% url 'reports' %}"><span class="icon is-small"><i
                                        class="fa-solid fa-newspaper"></i></span> &nbsp; Reports</a></li>
                        <br>
                        <li style="line-height: 1px"><a id="SideText" href="{% url 'diagrams' %}"><span class="icon is-small"><i
                                        class="fa-solid fa-diagram-project"></i></span> &nbsp; Diagrams</a></li>
                        <br>
                        <li style="line-height: 1px"><a id="SideText" href="{% url 'historical_data_logs' %}"><span class="icon is-small"><i
                                        class="fa-solid fa-box-archive"></i></span> &nbsp; Historical Data</a></li>
                    </ul>

                </nav>

                <img src="{% static 'images/logo01.png' %}" class="footer-images" alt="Sample image"
                    style="width: 100%; position: center; left: 0.3vw; margin-bottom: 10vh;">

            </aside>

            <main id="main_block" class="column main" style="padding-bottom: 100vh; padding-top: 12vh;">

                <br>
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}
                {% endif %}

                {% block content %}

                {% endblock %}
            </main>
        </div>
    </div>


</body>

<script>
    function startTime() {
        const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
        const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

        const today = new Date();
        let h = today.getHours();
        let m = today.getMinutes();
        let s = today.getSeconds();
        let y = today.getFullYear();
        let mon = today.getMonth() + 1;
        let d = today.getDate();

        let dayName = days[today.getDay()];
        let monthName = months[mon - 1];

        m = checkTime(m);
        s = checkTime(s);
        document.getElementById('Date').innerHTML = dayName + ", " + monthName + ", " + (mon) + "/" + d + "/" + y + "  " + h + ":" + m + ":" + s;
        setTimeout(startTime, 1000);
    }
    function checkTime(i) {
        if (i < 10) { i = "0" + i };  // add zero in front of numbers < 10
        return i;
    }
</script>

</html>

website/templates/charts.html
{% extends 'base.html' %}
{% block content %}

Under Progress

{% endblock %}

website/templates/data_logs_devices.html
{% extends 'base.html' %}

{% block content %}


<div class="col-md-12" style="margin: 1%;">
  <h1>Data Logs</h1>
  <br>

  <div class="row g-4">
    {% if records %}
    {% for record in records %}


    <div class="card" style="width: 18rem; margin-right: 1rem; background-color: #e0f1f1;">
      <div class="card-body">
        <h6 class="card-title">{{ record.device_name }}</h6>
        <p class="card-text">connection type: {{ record.connection_type }} : {{ record.port_conf }}</p>
        <p class="card-text">Activation: {{ record.signals }}</p>
        <p class="card-text"> Device Signal: <span class="device_status">{{ record.device_status }}</span></p>
        <p class="card-text">Manufacturer: {{ record.manufacturer}}</p>
        <a href='{% url "data_logs" record.id %}' class="btn btn-primary stretched-link">Data logs</a>

      </div>
    </div>

    {% endfor %}
    {%endif%}

  </div>
</div>




<script>

  const elements = document.querySelectorAll('.device_status');

  elements.forEach(element => {
    console.log(element.innerText.trim())
    if (element.innerText.trim() == 'Offline') {
      element.style.color = 'red'
    }
    else {
      element.style.color = 'green'
    }
  });

</script>
{% endblock %}

website/templates/devices.html
{% extends 'base.html' %}
{% block content %}

<div class="row" style="margin-right: 10px;">
    <div class="container">
        <div class="card" style="background-color: #23272b;">
            <div class="card-body">

                <h1 style="color: white;"> Devices {% if is_admin %} <a class="btn btn-light float-end"
                        href="{% url 'add_device' %}" role="button"><i class="fa-solid fa-plus"></i></a> {% endif %}
                </h1>

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <!-- <th scope="col"><input type="checkbox"></th> -->
                            <th scope="col" id="">ID</th>
                            <th scope="col" id="">Device Name</th>
                            <th scope="col" id="">Device Group</th>
                            <th scope="col" id="">Connection Type</th>
                            <th scope="col" id="">Activation</th>
                            <th scope="col" id="">Manufacturer</th>
                            <th scope="col" id="">Device Status</th>
                            {% if is_admin %}
                            <th scope="col">#</th>
                            {% endif %}

                        </tr>
                    </thead>
                    {% if devices %}
                    {% for device in devices %}
                    <tbody class="table-group-divider">
                        <tr>
                            <!-- <th scope="row"><input type="checkbox"></th> -->
                            <td>{{ forloop.counter }}</td>
                            <td>{{ device.device_name }}</td>
                            <td>{{ device.group }}</td>
                            <td>{{ device.connection_type }} : {{ device.port_conf }}</td>
                            <td>{{ device.signals }}</td>
                            <td>{{ device.manufacturer }}</td>
                            <td class="device_status">{{ device.device_status }}</td>
                            {% if is_admin %}
                            <td>
                                <a class="btn btn-dark" href='{% url "update_device" device.id %}' style="margin-right: 10px;"><i class="fa-solid fa-pen-to-square"></i></a>

                                <a class="btn btn-danger confirm-delete" href='{% url "delete_device" device.id %}'><i class="fa-solid fa-trash"></i></a>
                            </td>
                            {% endif %}

                        </tr>
                    </tbody>
                    {% endfor %}
                    {% endif %}
                </table>
            </div>
        </div>
    </div>
</div>


<div id="deleteModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <p>!!!Warning: Deleting a device will also delete all related data such as Registers, Data Logs, etc. Are you
            sure you want to proceed?</p>
        <button id="confirmDeleteBtn" class="btn btn-danger">Yes, delete</button>
    </div>
</div>



<script>
    const elements = document.querySelectorAll('.device_status');

    elements.forEach(element => {
        console.log(element.innerText.trim())
        if (element.innerText.trim() == 'Offline') {
            element.style.color = 'red'
        }
        else {
            element.style.color = 'green'
        }
    });

    document.addEventListener('DOMContentLoaded', function () {
        var deleteLinks = document.querySelectorAll('.confirm-delete');
        var modal = document.getElementById("deleteModal");
        var confirmDeleteBtn = document.getElementById("confirmDeleteBtn");
        var closeBtn = document.querySelector(".close");
        var deleteURL; // Variable to store the deletion URL

        deleteLinks.forEach(function (link) {
            link.addEventListener('click', function (event) {
                event.preventDefault(); // Prevent the default link behavior
                modal.style.display = "block"; // Display the modal
                deleteURL = link.getAttribute('href'); // Store the deletion URL
            });
        });

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }

        // Close the modal when the user clicks on the close button
        closeBtn.onclick = function () {
            modal.style.display = "none";
        }

        // Proceed with the deletion when the user clicks on confirm
        confirmDeleteBtn.onclick = function () {
            // Check if deleteURL is defined
            if (deleteURL) {
                window.location.href = deleteURL;
            }
        }
    });

</script>


<style>
    /* CSS for modal styling */
    .modal {
        display: none;
        /* Hidden by default */
        position: fixed;
        /* Stay in place */
        z-index: 1;
        /* Sit on top */
        left: 0;
        top: 0;
        width: 100%;
        /* Full width */
        height: 100%;
        /* Full height */
        overflow: auto;
        /* Enable scroll if needed */
        background-color: rgba(0, 0, 0, 0.4);
        /* Black w/ opacity */
    }

    .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px;
        border: 1px solid #888;
        width: 80%;
    }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }
</style>

{% endblock %}

website/templates/home.html
{% extends 'base.html' %}
{% block content %}

<!-- <div class="col-md-6 offset-md-3"> -->


<h1>welcome to the home page</h1>


{% endblock %}